-- DayGrid migration 0002 — accounts (ASP.NET Core Identity), Data Protection key ring and
-- per-user data isolation.
--
-- Runs inside one transaction (SchemaMigrator). No CREATE EXTENSION — valid on Azure Database
-- for PostgreSQL Flexible Server. Safe on a database that already holds data: every existing
-- row keeps user_id NULL ("legacy") until the first account registers, at which point the app
-- assigns all legacy rows to that account in the same transaction that creates it.

-- ---------------------------------------------------------------------------
-- Identity: users, roles and their satellite tables (snake_case names; mapped in
-- Infrastructure/Data/Configurations/IdentityConfigurations.cs).
-- ---------------------------------------------------------------------------
CREATE TABLE users (
    id                      uuid PRIMARY KEY,
    user_name               varchar(256) NULL,
    normalized_user_name    varchar(256) NULL,
    email                   varchar(256) NULL,
    normalized_email        varchar(256) NULL,
    email_confirmed         bool NOT NULL DEFAULT false,
    password_hash           text NULL,
    security_stamp          text NULL,
    concurrency_stamp       text NULL,
    phone_number            text NULL,
    phone_number_confirmed  bool NOT NULL DEFAULT false,
    two_factor_enabled      bool NOT NULL DEFAULT false,
    lockout_end             timestamptz NULL,
    lockout_enabled         bool NOT NULL DEFAULT true,
    access_failed_count     int NOT NULL DEFAULT 0,
    display_name            varchar(100) NOT NULL,
    created_at              timestamptz NOT NULL DEFAULT now(),
    last_login_at           timestamptz NULL
);

-- The email is the user name; both are unique (case-insensitively, via the normalized columns).
CREATE UNIQUE INDEX ux_users_normalized_user_name ON users (normalized_user_name);
CREATE UNIQUE INDEX ux_users_normalized_email ON users (normalized_email);

CREATE TABLE roles (
    id                 uuid PRIMARY KEY,
    name               varchar(256) NULL,
    normalized_name    varchar(256) NULL,
    concurrency_stamp  text NULL
);

CREATE UNIQUE INDEX ux_roles_normalized_name ON roles (normalized_name);

CREATE TABLE user_roles (
    user_id  uuid NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    role_id  uuid NOT NULL REFERENCES roles (id) ON DELETE CASCADE,
    PRIMARY KEY (user_id, role_id)
);

CREATE INDEX ix_user_roles_role_id ON user_roles (role_id);

CREATE TABLE user_claims (
    id           int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      uuid NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    claim_type   text NULL,
    claim_value  text NULL
);

CREATE INDEX ix_user_claims_user_id ON user_claims (user_id);

CREATE TABLE user_logins (
    login_provider         varchar(128) NOT NULL,
    provider_key           varchar(128) NOT NULL,
    provider_display_name  text NULL,
    user_id                uuid NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    PRIMARY KEY (login_provider, provider_key)
);

CREATE INDEX ix_user_logins_user_id ON user_logins (user_id);

CREATE TABLE user_tokens (
    user_id         uuid NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    login_provider  varchar(128) NOT NULL,
    name            varchar(128) NOT NULL,
    value           text NULL,
    PRIMARY KEY (user_id, login_provider, name)
);

CREATE TABLE role_claims (
    id           int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_id      uuid NOT NULL REFERENCES roles (id) ON DELETE CASCADE,
    claim_type   text NULL,
    claim_value  text NULL
);

CREATE INDEX ix_role_claims_role_id ON role_claims (role_id);

-- Fixed ids so code and tests can refer to them (Infrastructure/Identity/AppRoles.cs).
INSERT INTO roles (id, name, normalized_name, concurrency_stamp) VALUES
    ('3f0c8f1e-7a52-4d0e-9a51-6b1f2d3c4e01', 'User',  'USER',  '3f0c8f1e-7a52-4d0e-9a51-6b1f2d3c4e01'),
    ('3f0c8f1e-7a52-4d0e-9a51-6b1f2d3c4e02', 'Admin', 'ADMIN', '3f0c8f1e-7a52-4d0e-9a51-6b1f2d3c4e02');

-- ---------------------------------------------------------------------------
-- ASP.NET Core Data Protection key ring (auth cookies / tokens survive restarts and are shared by
-- every App Service instance).
-- ---------------------------------------------------------------------------
CREATE TABLE data_protection_keys (
    id             int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    friendly_name  text NULL,
    xml            text NULL
);

-- ---------------------------------------------------------------------------
-- Tenant column on every user-owned table. Nullable only so pre-existing rows survive until the
-- first account claims them; the application always stamps it on insert.
-- ---------------------------------------------------------------------------
ALTER TABLE checklists            ADD COLUMN user_id uuid NULL REFERENCES users (id) ON DELETE CASCADE;
ALTER TABLE checklist_items       ADD COLUMN user_id uuid NULL REFERENCES users (id) ON DELETE CASCADE;
ALTER TABLE checklist_completions ADD COLUMN user_id uuid NULL REFERENCES users (id) ON DELETE CASCADE;
ALTER TABLE timetable_templates   ADD COLUMN user_id uuid NULL REFERENCES users (id) ON DELETE CASCADE;
ALTER TABLE timetable_blocks      ADD COLUMN user_id uuid NULL REFERENCES users (id) ON DELETE CASCADE;
ALTER TABLE timetable_assignments ADD COLUMN user_id uuid NULL REFERENCES users (id) ON DELETE CASCADE;
ALTER TABLE day_overrides         ADD COLUMN user_id uuid NULL REFERENCES users (id) ON DELETE CASCADE;
ALTER TABLE future_tasks          ADD COLUMN user_id uuid NULL REFERENCES users (id) ON DELETE CASCADE;
ALTER TABLE reminders             ADD COLUMN user_id uuid NULL REFERENCES users (id) ON DELETE CASCADE;
ALTER TABLE notification_log      ADD COLUMN user_id uuid NULL REFERENCES users (id) ON DELETE CASCADE;
ALTER TABLE app_settings          ADD COLUMN user_id uuid NULL REFERENCES users (id) ON DELETE CASCADE;
ALTER TABLE simple_tasks          ADD COLUMN user_id uuid NULL REFERENCES users (id) ON DELETE CASCADE;
ALTER TABLE constant_expenses     ADD COLUMN user_id uuid NULL REFERENCES users (id) ON DELETE CASCADE;
ALTER TABLE varying_expenses      ADD COLUMN user_id uuid NULL REFERENCES users (id) ON DELETE CASCADE;
ALTER TABLE completed_spends      ADD COLUMN user_id uuid NULL REFERENCES users (id) ON DELETE CASCADE;

CREATE INDEX ix_checklists_user_id            ON checklists (user_id);
CREATE INDEX ix_checklist_items_user_id       ON checklist_items (user_id);
CREATE INDEX ix_checklist_completions_user_id ON checklist_completions (user_id);
CREATE INDEX ix_timetable_templates_user_id   ON timetable_templates (user_id);
CREATE INDEX ix_timetable_blocks_user_id      ON timetable_blocks (user_id);
CREATE INDEX ix_timetable_assignments_user_id ON timetable_assignments (user_id);
CREATE INDEX ix_future_tasks_user_id          ON future_tasks (user_id);
CREATE INDEX ix_reminders_user_id             ON reminders (user_id);
CREATE INDEX ix_notification_log_user_id      ON notification_log (user_id);
CREATE INDEX ix_simple_tasks_user_id          ON simple_tasks (user_id);
CREATE INDEX ix_constant_expenses_user_id     ON constant_expenses (user_id);
CREATE INDEX ix_varying_expenses_user_id      ON varying_expenses (user_id);
CREATE INDEX ix_completed_spends_user_id      ON completed_spends (user_id);

-- ---------------------------------------------------------------------------
-- Global uniques become per user.
-- ---------------------------------------------------------------------------
-- One override per user per date (was: one per date for the whole database).
DROP INDEX ux_day_overrides_date;
CREATE UNIQUE INDEX ux_day_overrides_user_date ON day_overrides (user_id, date);

-- ux_checklist_completions_item_date stays as is: an item belongs to exactly one user, so
-- (checklist_item_id, occurrence_date) is already per user.

-- app_settings: from a single-row table (id = 1) to one row per user.
ALTER TABLE app_settings DROP CONSTRAINT ck_app_settings_singleton;
ALTER TABLE app_settings ALTER COLUMN id DROP DEFAULT;
ALTER TABLE app_settings ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
SELECT setval(pg_get_serial_sequence('app_settings', 'id'), GREATEST(COALESCE((SELECT max(id) FROM app_settings), 0), 1));
CREATE UNIQUE INDEX ux_app_settings_user_id ON app_settings (user_id);
